name: Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
        coverage: none
        
    - name: Install dependencies
      run: |
        composer install --no-dev --optimize-autoloader --no-interaction --no-progress
        
    - name: Build assets
      run: |
        npm ci
        npm run build
        
    - name: Create deployment package
      run: |
        mkdir deployment
        # Copy necessary files
        cp -r app bootstrap config database public resources routes storage vendor deployment/
        cp artisan composer.json deployment/
        # Generate app key
        cd deployment
        php artisan key:generate --no-interaction --force
        # Add basic .env configuration
        echo "APP_NAME=Jochan Tech" >> .env
        echo "APP_ENV=production" >> .env
        echo "APP_DEBUG=false" >> .env
        echo "APP_URL=https://yourdomain.com" >> .env
        cd ..
        
    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deployment/
        server-dir: /public_html/
EOF